# Generated by Django 5.2.3 on 2025-06-23 17:27

import django.db.models.deletion
import info.models_agent
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mobile", models.CharField(max_length=10)),
                ("company_name", models.CharField(max_length=100)),
                ("office_address", models.TextField()),
                ("project_location", models.CharField(max_length=100)),
                (
                    "company_logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=info.models_agent.agent_logo_upload_path,
                    ),
                ),
                (
                    "company_rera_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PropertyVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=100)),
                ("area", models.CharField(max_length=150)),
                ("price", models.IntegerField()),
                (
                    "property_type",
                    models.CharField(
                        choices=[("Buy", "Buy"), ("Rent", "Rent")], max_length=10
                    ),
                ),
                (
                    "properties",
                    models.CharField(
                        choices=[
                            ("Plot", "Plot"),
                            ("1BHK", "1BHK"),
                            ("2BHK", "2BHK"),
                            ("3BHK", "3BHK"),
                            ("4BHK", "4BHK"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "market_price_per_sqft",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("token_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "property_size_sqft",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("video", models.FileField(upload_to="property_videos/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="info.agentprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mobile", models.CharField(max_length=15)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
