# Generated by Django 5.2.3 on 2025-06-30 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentprofile",
            name="experience",
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="agentprofile",
            name="company_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
