# Generated by Django 5.2.3 on 2025-06-19 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PropertyVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("area", models.CharField(max_length=150)),
                ("price_min", models.IntegerField()),
                ("price_max", models.IntegerField()),
                (
                    "property_type",
                    models.CharField(
                        choices=[("Plot", "Plot"), ("Rent", "Rent")], max_length=10
                    ),
                ),
                (
                    "market_price_per_sqft",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("token_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "property_size_sqft",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("description", models.TextField(blank=True)),
                ("video", models.FileField(upload_to="property_videos/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="info.agentprofile",
                    ),
                ),
            ],
        ),
    ]
