# Generated by Django 5.2.3 on 2025-06-30 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0002_agentprofile_experience_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertyvideo",
            name="payment_condition",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="propertyvideo",
            name="rera",
            field=models.CharField(
                choices=[("Approved", "Approved"), ("Pending", "Pending")],
                default=1,
                max_length=10,
            ),
            preserve_default=False,
        ),
    ]
