# Generated by Django 5.2.3 on 2025-06-19 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0002_propertyvideo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="propertyvideo",
            name="description",
        ),
        migrations.RemoveField(
            model_name="propertyvideo",
            name="title",
        ),
    ]
