# Generated by Django 5.2.3 on 2025-06-30 22:39

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0003_propertyvideo_payment_condition_propertyvideo_rera"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentprofile",
            name="deal",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[("All", "All"), ("Plot", "Plot"), ("Rent", "Rent")],
                default=list,
                max_length=13,
            ),
        ),
    ]
