# Generated by Django 5.2.3 on 2025-06-21 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0004_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertyvideo",
            name="property_type",
            field=models.CharField(
                choices=[("Buy", "Buy"), ("Rent", "Rent")], max_length=10
            ),
        ),
    ]
