# Generated by Django 5.2.3 on 2025-06-30 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0004_agentprofile_deal"),
    ]

    operations = [
        migrations.CreateModel(
            name="DealType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name="agentprofile",
            name="deal",
        ),
        migrations.AddField(
            model_name="agentprofile",
            name="deal",
            field=models.ManyToManyField(to="info.dealtype"),
        ),
    ]
