# Generated by Django 5.2.3 on 2025-06-30 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0005_dealtype_remove_agentprofile_deal_agentprofile_deal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertyvideo",
            name="rera",
            field=models.CharField(
                blank=True,
                choices=[("Approved", "Approved"), ("Pending", "Pending")],
                max_length=10,
                null=True,
            ),
        ),
    ]
