# Generated by Django 5.2.3 on 2025-06-22 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0005_alter_propertyvideo_property_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertyvideo",
            name="properties",
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
