# Generated by Django 5.2.3 on 2025-07-07 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0006_alter_propertyvideo_rera"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentprofile",
            name="role",
            field=models.CharField(default="Agent", max_length=10),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="role",
            field=models.CharField(default="user", max_length=10),
        ),
    ]
