# Generated by Django 5.2.3 on 2025-06-22 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0006_propertyvideo_properties"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertyvideo",
            name="properties",
            field=models.CharField(
                choices=[
                    ("Plot", "Plot"),
                    ("1BHK", "1BHK"),
                    ("2BHK", "2BHK"),
                    ("3BHK", "3BHK"),
                    ("4BHK", "4BHK"),
                ],
                max_length=10,
            ),
        ),
    ]
