# Generated by Django 5.2.3 on 2025-06-22 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0007_alter_propertyvideo_properties"),
    ]

    operations = [
        migrations.RenameField(
            model_name="propertyvideo",
            old_name="price_max",
            new_name="price",
        ),
        migrations.RemoveField(
            model_name="propertyvideo",
            name="price_min",
        ),
    ]
