# Generated by Django 5.2.3 on 2025-07-07 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0007_agentprofile_role_userprofile_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="propertyvideo",
            name="market_price_per_sqft",
        ),
        migrations.AddField(
            model_name="propertyvideo",
            name="guideline_per_sqft",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="propertyvideo",
            name="property_size_sqft",
            field=models.IntegerField(),
        ),
    ]
