# Generated by Django 5.2.1 on 2025-07-08 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0008_remove_propertyvideo_market_price_per_sqft_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentprofile",
            name="experience",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="propertyvideo",
            name="properties",
            field=models.CharField(
                choices=[
                    ("Plot", "Plot"),
                    ("Raw House", "Raw House"),
                    ("1BHK", "1BHK"),
                    ("2BHK", "2BHK"),
                    ("3BHK", "3BHK"),
                    ("4BHK", "4BHK"),
                ],
                max_length=10,
            ),
        ),
    ]
