# Generated by Django 5.2.1 on 2025-07-09 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0009_alter_agentprofile_experience_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertyvideo",
            name="properties",
            field=models.CharField(
                choices=[
                    ("Plots & Houses", [("Plot", "Plot"), ("Raw House", "Raw House")]),
                    (
                        "Residential",
                        [
                            ("1BHK", "1BHK"),
                            ("2BHK", "2BHK"),
                            ("3BHK", "3BHK"),
                            ("4BHK", "4BHK"),
                        ],
                    ),
                    (
                        "Commercial",
                        [
                            ("Office", "Office"),
                            ("Shop", "Shop"),
                            ("Showroom", "Showroom"),
                        ],
                    ),
                ],
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="ContactLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contact_type",
                    models.CharField(
                        choices=[("WhatsApp", "WhatsApp"), ("Call", "Call")],
                        max_length=10,
                    ),
                ),
                ("contact_datetime", models.DateTimeField(auto_now_add=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="info.agentprofile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="info.propertyvideo",
                    ),
                ),
            ],
        ),
    ]
