# Generated by Django 5.2.1 on 2025-07-09 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0010_alter_propertyvideo_properties_contactlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactlog",
            name="agent_mobile",
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contactlog",
            name="user_mobile",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
