# Generated by Django 5.2.3 on 2025-07-15 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0011_contactlog_agent_mobile_contactlog_user_mobile"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertyvideo",
            name="project_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
