# Generated by Django 5.2.1 on 2025-09-11 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0012_propertyvideo_project_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertyvideo",
            name="property_size_sqft",
            field=models.CharField(max_length=100),
        ),
    ]
