# Generated by Django 5.2.3 on 2025-09-17 18:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("info", "0013_alter_propertyvideo_property_size_sqft"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertyvideo",
            name="processing",
            field=models.BooleanField(default=False),
        ),
    ]
