# Generated by Django 5.2.3 on 2025-09-29 17:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0014_propertyvideo_processing"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactlog",
            options={"ordering": ["-contact_datetime"]},
        ),
        migrations.AlterModelOptions(
            name="propertyvideo",
            options={"ordering": ["-uploaded_at"]},
        ),
        migrations.AlterField(
            model_name="agentprofile",
            name="mobile",
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AddIndex(
            model_name="contactlog",
            index=models.Index(
                fields=["agent", "-contact_datetime"], name="idx_agent_contact"
            ),
        ),
        migrations.AddIndex(
            model_name="contactlog",
            index=models.Index(
                fields=["user", "-contact_datetime"], name="idx_user_contact"
            ),
        ),
        migrations.AddIndex(
            model_name="contactlog",
            index=models.Index(fields=["-contact_datetime"], name="idx_contact_time"),
        ),
        migrations.AddIndex(
            model_name="propertyvideo",
            index=models.Index(fields=["-uploaded_at"], name="idx_uploaded_at"),
        ),
        migrations.AddIndex(
            model_name="propertyvideo",
            index=models.Index(fields=["city", "area"], name="idx_city_area"),
        ),
        migrations.AddIndex(
            model_name="propertyvideo",
            index=models.Index(fields=["property_type"], name="idx_property_type"),
        ),
        migrations.AddIndex(
            model_name="propertyvideo",
            index=models.Index(fields=["city", "property_type"], name="idx_city_type"),
        ),
        migrations.AddIndex(
            model_name="propertyvideo",
            index=models.Index(fields=["price"], name="idx_price"),
        ),
        migrations.AddIndex(
            model_name="propertyvideo",
            index=models.Index(
                fields=["agent", "-uploaded_at"], name="idx_agent_upload"
            ),
        ),
        migrations.AddIndex(
            model_name="propertyvideo",
            index=models.Index(
                fields=["city", "area", "property_type"], name="idx_full_filter"
            ),
        ),
    ]
